# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  RACKET_DIR: $(Agent.BuildDirectory)/racket
  RACKET_VERSION: 7.2
  DISPLAY: :99.0

steps:
- script: bash ./etc/scripts/install-racket.sh
  displayName: 'Installing Racket RACKET_VERSION'

- script: $(RACKET_DIR)/bin/racket build.rkt
  displayName: 'Building Application'
